### PR TITLE
Npm updates

### PR DESCRIPTION
**Pull request by brettz9**
Builds on #64

- chore: update deps. (minor or patch bumps except `filesize`) and devDeps

Also updates per latest `prettier` linting

Btw, it'd be great to get a new release, after reviews, as I'd love to point to the stable version of `rollup-plugin-filesize` in `filesize-badger`. Thanks!

### CODE REVIEW

**Comment by brettz9** [comment]
Note that what you see in your IDE may show violations now despite `prettier` not complaining. That is because `eslint-plugin-prettier` is behind: https://github.com/prettier/eslint-plugin-prettier/pull/281

**Comment by ritz078** [comment]
This has conflicts too.

**Comment by brettz9** [comment]
Sure, rebased.

**Comment by ritz078** [comment]
Thanks for your contribution @brettz9 ❤️

**Pull request merged**
