### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by LeviPesin**
Fixes https://github.com/ritz078/rollup-plugin-filesize/issues/107

### CODE REVIEW

**Comment by ritz078** [comment]
@guipace Are the tests passing locally ?

**Comment by LeviPesin** [comment]
I think the tests didn't run because it is the first time I'm contributing to this repository (so the workflow should be approved by maintainer).

**Comment by guipace** [comment]
> @guipace Are the tests passing locally ?

I'm getting all sorts of errors trying to run `yarn install`. I'm not going to touch this without knowing the context or having worked on it before. I was trying to resolve a dependabot alert on a repo of mine that depends on this plugin.

image

image

**Comment by LeviPesin** [comment]
Maybe we can update only pacote then? Seems like most problems come from the fact it's outdated.

**Comment by ritz078** [comment]
This PR breaks the module. Does https://github.com/ritz078/rollup-plugin-filesize/pull/114 fixes your issue ?

It shows moderate issues in ava which is a dev dependency but all other issues are gone. Updating ava is going to take a bit longer.

**Comment by LeviPesin** [comment]
Seems to resolve, thank you!

**Pull request closed without merging**
