### PR TITLE
Update terser to 5.5.1

### LINKED ISSUE #87: New release with terser 5.2
Terser 5.2 supports ES2020, which importantly has optional chaining and nullish coalescing: https://github.com/terser/terser/issues/643

### PR DESCRIPTION
**Pull request by justinfagnani**
This fixes #87 and adds support for optional chaining and nullish coalescing.

### CODE REVIEW

**Comment by justinfagnani** [comment]
@ritz078 we're in a bit of a bind with trying to use ES2020 and this plugin. Updating Terser was pretty painless. Could you take a look? Thanks!

**Review by ritz078 — APPROVED** [review]

**Comment by ritz078** [comment]
Thank you for your contribution 🎉

**Comment by ritz078** [comment]
This has been published as 9.1.0

**Comment by justinfagnani** [comment]
Thanks so much @ritz078!

**Pull request merged**
